name: CI workflow
on: 
  push: ### Event on push to the master branch
   branches: [main] 
  pull_request: ### Event on pull request
    types: [opened, reopened] ## Event when PR is opened or reopened
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - 
# publish  ---> publish job
#   runs-on: ubuntu-latest
#   needs: build --> depends on build job so job would run serially
#   steps: 

  #on:
  # release:
  # types: [pulish] usually for packaging workflow whenever a release is published
  #
    