name: CI workflow
on: 
  push: ### Event on push to the master branch
   branches: [main] 
  pull_request: ### Event on pull request
    types: [opened, reopened] ## Event when PR is opened or reopened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
     -
      name: checkout
      uses: actions/checkout@v3
     - 
      name: Install dependencies
      run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
     -
       name: Lint with Flaske8
       run: | 
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
     -
       name: Run unit tests with nose
       run: | 
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

# publish  ---> publish job
#   runs-on: ubuntu-latest
#   needs: build --> depends on build job so job would run serially
#   steps: 

  #on:
  # release:
  # types: [pulish] usually for packaging workflow whenever a release is published
  #
    